### PR TITLE
Loop over supported CUDA versions to find installed CUDA on Windows and Mac.

### LINKED ISSUE #472: GpuArrayException: Could not load "nvrtc64_90.dll": Le module spécifié est introuvable.
Just to report a very strange issue about libgpuarray on Windows (8.1 64 bits). It now looks for a DLL named `nvrtc64_90.dll` but it can't find it on my computer:

```
(python2) HPPC@NOTORAPTOR-HP C:\Users\HPPC\mila\dev\git\theano
> set THEANO_FLAGS=device=cuda

(python2) HPPC@NOTORAPTOR-HP C:\Users\HPPC\mila\dev\git\theano
> python -c "import theano"

Tmp 9000 Major 9 Minor 0
ERROR (theano.gpuarray): Could not initialize pygpu, support disabled
Traceback (most recent call last):
  File "theano\gpuarray\__init__.py", line 179, in <module>
    use(config.device)
  File "theano\gpuarray\__init__.py", line 166, in use
    init_dev(device, preallocate=preallocate)
  File "theano\gpuarray\__init__.py", line 65, in init_dev
    sched=config.gpuarray.sched)
  File "pygpu\gpuarray.pyx", line 634, in pygpu.gpuarray.init (pygpu/gpuarray.c:9436)
  File "pygpu\gpuarray.pyx", line 584, in pygpu.gpuarray.pygpu_init (pygpu/gpuarray.c:9127)
  File "pygpu\gpuarray.pyx", line 1057, in pygpu.gpuarray.GpuContext.__cinit__ (pygpu/gpuarray.c:13429)
GpuArrayException: Could not load "nvrtc64_90.dll": Le module spécifié est introuvable.
```

Looking into NVIDIA bin folder (`C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin`), I found `nvrtc64_80.dll` but not `nvrtc64_90.dll`:

image

**NB**: it seems the problem comes from library version detection, based on the value returned by `cuDriverGetVersion()`:
https://github.com/Theano/libgpuarray/blob/master/src/gpuarray_buffer_cuda.c#L143
https://github.com/Theano/libgpuarray/blob/master/src/loaders/libnvrtc.c#L30

But it worked some days ago. I just reminded that I have updated my NVIDIA driver some days ago too, but it should not cause any problem, should it ?

@abergeron @nouiz @lamblin

### PR DESCRIPTION
**Pull request by notoraptor**
Fix #472 . Tested on my Windows 8.1 64 bits with Python 2.7.13 Anaconda 64 bits.

When compiled as Debug version:
```
(python2) HPPC@NOTORAPTOR-HP C:\Users\HPPC\mila\dev\git\theano
> echo %THEANO_FLAGS%
device=cuda0

(python2) HPPC@NOTORAPTOR-HP C:\Users\HPPC\mila\dev\git\theano
> python -c "import theano"
ERROR 18: Could not load "nvrtc64_90.dll": Le module spécifié est introuvable.

Detected CUDA 8.0.
Loading cuBLAS 8.0.
Using cuDNN version 6020 on context None
Mapped name None to device cuda0: GeForce 840M (0000:0A:00.0)
```

@nouiz @abergeron @lamblin .

### CODE REVIEW

File: src/gpuarray_buffer_cuda.c [hunk 1]
```diff
@@ -147,13 +148,49 @@ static int setup_lib(void) {
         return error_set(global_err, GA_IMPL_ERROR, "cuDriverGetVersion failed");
       major = tmp / 1000;
       minor = (tmp / 10) % 10;
+      #if defined(WIN32) || defined(_WIN32) || defined(WIN64) || defined(_WIN64) || defined(__APPLE__)
```
Comment (nouiz) [inline src/gpuarray_buffer_cuda.c]: why not also on linux?

File: src/gpuarray_buffer_cuda.c [hunk 2]
```diff
@@ -147,13 +148,49 @@ static int setup_lib(void) {
...
+      /* We will dynamically search the right CUDA version only on Windows and Macintosh systems,
+      and only if user has not explicitely specified GPUARRAY_CUDA_VERSION. */
+      search_version = 1;
+      #endif
     } else {
       major = ver[0] - '0';
       minor = ver[1] - '0';
     }
+    /* NB: next line will cause problems if a CUDA 10.0 (or 9.11) is released in the future. */
```
Comment (nouiz) [inline src/gpuarray_buffer_cuda.c]: good catch. Make an issue about that. cuda 9 is annouced, so in 1 or 2 year we should have an cuda 10 I guess.

File: src/gpuarray_buffer_cuda.c [hunk 3]
```diff
@@ -147,13 +148,49 @@ static int setup_lib(void) {
...
     if (major > 9 || major < 0 || minor > 9 || minor < 0)
       return error_fmt(global_err, GA_VALUE_ERROR, "Invalid cuda version: %d.%d", major, minor);
-    res = load_libnvrtc(major, minor, global_err);
+    if (!search_version) {
```
Comment (nouiz) [inline src/gpuarray_buffer_cuda.c]: I'll let @abergeron review this part.

File: src/gpuarray_buffer_cuda.c (hunk 1 above)
Comment (notoraptor) [inline src/gpuarray_buffer_cuda.c]: Based on code in libnvrtc.c ( https://github.com/Theano/libgpuarray/blob/master/src/loaders/libnvrtc.c#L49 ), we just look for `libnvrtc.so` on Linux (without explicitely specifying a version).

File: src/gpuarray_buffer_cuda.c (hunk 2 above)
Comment (notoraptor) [inline src/gpuarray_buffer_cuda.c]: Ok!

File: src/gpuarray_buffer_cuda.c [hunk 4]
```diff
@@ -147,13 +148,49 @@ static int setup_lib(void) {
...
+      res = load_libnvrtc(major, minor, global_err);
+    } else {
+      /* First case in next array is reserved to eventually receive the version returned by cuDriverGetVersion(). */
+      int versions[] = {-1, 80, 75};
```
Comment (abergeron) [inline src/gpuarray_buffer_cuda.c]: We still support 7.0.

Also, since cuda 10 is not so far away, make this a list of pair of ints instead to explicitly list the majors/minors that we support.

File: src/gpuarray_buffer_cuda.c (hunk 1 above)
Comment (abergeron) [inline src/gpuarray_buffer_cuda.c]: It is true that we only look at a specific file for windows, but I would rather not spread the assumption here.

We may devise a way to load a specific version of cuda on linux/mac later, and I would rather that the necessary components are in place at the upper levels.  Also this makes the code more complex for no benefit.

File: src/gpuarray_buffer_cuda.c (hunk 2 above)
Comment (abergeron) [inline src/gpuarray_buffer_cuda.c]: If we can look for all supported versions, then we can probably drop the environment variable, which would solve the problem.

File: src/gpuarray_buffer_cuda.c [hunk 5]
```diff
@@ -147,13 +148,49 @@ static int setup_lib(void) {
...
+      for (i = 1; i < versions_length && versions[i] != current_version; ++i);
+      if (i == versions_length) {
+        /* Current version not found in the list of versions. We add it at top of the list. */
+        versions[0] = current_version;
+        /* We will iterate on versions from the first. */
+        i = 0;
+      } else {
+        /* Current version found in the list of known versions. No need to add it to the list. */
+        i = 1;
+      };
```
Comment (abergeron) [inline src/gpuarray_buffer_cuda.c]: Can we just try a load with the minor/major from cuDriverGetVersion and then fallback to the list.  This seems overly complicated.

File: src/gpuarray_buffer_cuda.c [hunk 6]
```diff
@@ -147,13 +148,49 @@ static int setup_lib(void) {
...
+        major = versions[i] / 10;
+        minor = versions[i] % 10;
+        res = load_libnvrtc(major, minor, global_err);
+        ++i;
+      } while(res != GA_NO_ERROR && i < versions_length);
+      #ifdef DEBUG
+      if (res == GA_NO_ERROR)
+        fprintf(stderr, "Detected CUDA %d.%d.\n", major, minor);
+      else
+        fprintf(stderr, "Unable to detect a CUDA version.\n");
```
Comment (abergeron) [inline src/gpuarray_buffer_cuda.c]: I would probably push that message back in the loader for nvrtc, similar to what you did for cublas.  The code in gpuarray_buffer_cuda is already kind of too large.

File: src/gpuarray_buffer_cuda.c (hunk 4 above)
Comment (notoraptor) [inline src/gpuarray_buffer_cuda.c]: By `list of pair of ints`, do you mean something like
```C
int versions[][2] = {{8, 0}, {7, 5}, {7,  0}};
```
?

Comment (abergeron) [inline src/gpuarray_buffer_cuda.c]: If that works, yes.

File: src/gpuarray_buffer_cuda.c (hunk 5 above)
Comment (notoraptor) [inline src/gpuarray_buffer_cuda.c]: I did that to avoid testing twice a same version that is not installed (e.g. if cuDriverGetVersion() returns 80, then 80 will already be in the list of supported versions).

Do you anyway want the fallback strategy ?

**Comment by notoraptor** [comment]
@abergeron updated. This should be tested on Mac also. Check how I support >9 versions.

NB: for a CUDA version like `10.1`, current code will look for `nvrtc64_101.dll`. For a version like `10.12`, it will look for `nvrtc64_1012.dll` (pattern `%d%d`). Not sure if it is the right pattern to use (maybe should I consider that `10.1 => 1010` and `10.12 => 1012`, or rather `10.1 => 1001` and `10.12 => 1012` ?). I don't know if NVIDIA may release a minor version > 9.

File: src/gpuarray_buffer_cuda.c [hunk 7]
```diff
@@ -140,20 +140,25 @@ static int setup_lib(void) {
...
+    if (err != CUDA_SUCCESS)
+      return error_set(global_err, GA_IMPL_ERROR, "cuDriverGetVersion failed");
+    major = tmp / 1000;
+    minor = (tmp / 10) % 10;
+    /* Let's try to load a nvrtc corresponding to detected CUDA version. */
     res = load_libnvrtc(major, minor, global_err);
+    if (res != GA_NO_ERROR) {
+      /* Else, let's try to find a nvrtc corresponding to supported CUDA versions. */
+      int versions[][2] = {{8, 0}, {7, 5}, {7, 0}};
+      int versions_length = sizeof(versions) / (2 * sizeof(int));
```
Comment (abergeron) [inline src/gpuarray_buffer_cuda.c]: rather than `2 * sizeof(int)` use `sizeof(versions[0])`

File: src/loaders/libcublas.c [hunk 8]
```diff
@@ -41,21 +45,22 @@ int load_libcublas(int major, int minor, error *e) {
...
-    char libname[] = "cublas64_??.dll";
+    const char* libname_pattern = "cublas64_%d%d.dll";
+    char libname[64];
 
-    libname[9] = DIGITS[major];
-    libname[10] = DIGITS[minor];
+    #ifdef DEBUG
+    fprintf(stderr, "Loading cuBLAS %d.%d.\n", major, minor);
+    #endif
+    sprintf(libname, libname_pattern, major, minor);
```
Comment (abergeron) [inline src/loaders/libcublas.c]: I object to sprintf.  Use snprintf at the minimum.

Also check for errors and report them.  We don't want to use a truncated name for loading.

Finally, have the format string in the arguments to snprintf().

**Comment by abergeron** [comment]
We'll see about the name pattern for cuda 10 when it is released.  No need to worry too much about this now.

**Comment by notoraptor** [comment]
@abergeron Updated.

**Comment by abergeron** [comment]
Code was mostly fine, I was just tired of back and forth for little gain, so I fixed the few remaining style issues.

**Comment by notoraptor** [comment]
Tests succeeded (also tested on my computer).
